import type { CaseDefinition, CaseSettings } from '@/types/cases';

export const DEFAULT_CASE_SETTINGS: CaseSettings = {
  casesEnabled: true,
  adminOnlyOpen: false,
};

export const CASES_SEED: CaseDefinition[] = [
  {
    id: 'crimson',
    name: 'Багровый',
    description: '',
    price: 99,
    imageUrl: '/cases/8f2b7c73-0c0f-4182-bde1-a4b19f2dda5f.png',
    accent: '#ff4d4d',
    isActive: true,
    items: [
      { id: 1, caseId: 'crimson', name: 'Crimson Hammer', category: 'Молоток', rarity: 'common', sellPrice: 40, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 0 },
      { id: 2, caseId: 'crimson', name: 'Rust Garage', category: 'Гаражная дверь', rarity: 'common', sellPrice: 55, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 1 },
      { id: 3, caseId: 'crimson', name: 'Ember Hoodie', category: 'Худи', rarity: 'common', sellPrice: 60, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 2 },
      { id: 4, caseId: 'crimson', name: 'Ash Bag', category: 'Спальный мешок', rarity: 'common', sellPrice: 45, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 3 },
      { id: 5, caseId: 'crimson', name: 'Bloodsunset MP5', category: 'Пулемёт', rarity: 'rare', sellPrice: 320, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 4 },
      { id: 6, caseId: 'crimson', name: 'Crimson AR', category: 'Штурмовая винтовка', rarity: 'rare', sellPrice: 360, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 5 },
      { id: 7, caseId: 'crimson', name: 'Demon Mask', category: 'Маска', rarity: 'mythical', sellPrice: 1250, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 6 },
      { id: 8, caseId: 'crimson', name: 'Inferno AK', category: 'Штурмовая винтовка', rarity: 'mythical', sellPrice: 2600, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 7 },
    ],
  },
  {
    id: 'toxic',
    name: 'Токсичный',
    description: '',
    price: 149,
    imageUrl: '/cases/091e651f-e0c9-4490-aede-976b60da4414.png',
    accent: '#46c46a',
    isActive: true,
    items: [
      { id: 9, caseId: 'toxic', name: 'Swamp Hammer', category: 'Молоток', rarity: 'common', sellPrice: 45, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 0 },
      { id: 10, caseId: 'toxic', name: 'Mutant Hoodie', category: 'Худи', rarity: 'common', sellPrice: 60, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 1 },
      { id: 11, caseId: 'toxic', name: 'Bog Garage', category: 'Гаражная дверь', rarity: 'common', sellPrice: 70, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 2 },
      { id: 12, caseId: 'toxic', name: 'Spore Bag', category: 'Спальный мешок', rarity: 'common', sellPrice: 50, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 3 },
      { id: 13, caseId: 'toxic', name: 'Radiation Tommy', category: 'Пулемёт', rarity: 'rare', sellPrice: 380, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 4 },
      { id: 14, caseId: 'toxic', name: 'Toxic AR', category: 'Штурмовая винтовка', rarity: 'rare', sellPrice: 410, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 5 },
      { id: 15, caseId: 'toxic', name: 'Biohazard Mask', category: 'Маска', rarity: 'mythical', sellPrice: 1400, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 6 },
      { id: 16, caseId: 'toxic', name: 'Chernobyl M249', category: 'Пулемёт', rarity: 'mythical', sellPrice: 2900, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 7 },
    ],
  },
  {
    id: 'frost',
    name: 'Ледяной',
    description: '',
    price: 199,
    imageUrl: '/cases/47d51e0a-ca8a-4a99-9ed3-379945be5e52.png',
    accent: '#4aa3ff',
    isActive: true,
    items: [
      { id: 17, caseId: 'frost', name: 'Frost Hammer', category: 'Молоток', rarity: 'common', sellPrice: 55, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 0 },
      { id: 18, caseId: 'frost', name: 'Glacier Hoodie', category: 'Худи', rarity: 'common', sellPrice: 70, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 1 },
      { id: 19, caseId: 'frost', name: 'Ice Garage', category: 'Гаражная дверь', rarity: 'common', sellPrice: 80, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 2 },
      { id: 20, caseId: 'frost', name: 'Snow Bag', category: 'Спальный мешок', rarity: 'common', sellPrice: 60, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 3 },
      { id: 21, caseId: 'frost', name: 'Blizzard MP5', category: 'Пулемёт', rarity: 'rare', sellPrice: 440, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 4 },
      { id: 22, caseId: 'frost', name: 'Arctic AR', category: 'Штурмовая винтовка', rarity: 'rare', sellPrice: 480, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 5 },
      { id: 23, caseId: 'frost', name: 'Cryogen Mask', category: 'Маска', rarity: 'mythical', sellPrice: 1600, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 6 },
      { id: 24, caseId: 'frost', name: 'Absolute Zero L96', category: 'Снайперская винтовка', rarity: 'mythical', sellPrice: 3200, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 7 },
    ],
  },
  {
    id: 'phantom',
    name: 'Призрачный',
    description: '',
    price: 249,
    imageUrl: '/cases/65e529d4-e8e8-40ff-b65e-e66ba08287fe.png',
    accent: '#c8d2dc',
    isActive: true,
    items: [
      { id: 25, caseId: 'phantom', name: 'Bone Hammer', category: 'Молоток', rarity: 'common', sellPrice: 60, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 0 },
      { id: 26, caseId: 'phantom', name: 'Shroud Hoodie', category: 'Худи', rarity: 'common', sellPrice: 80, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 1 },
      { id: 27, caseId: 'phantom', name: 'Mist Garage', category: 'Гаражная дверь', rarity: 'common', sellPrice: 95, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 2 },
      { id: 28, caseId: 'phantom', name: 'Ash Bag', category: 'Спальный мешок', rarity: 'common', sellPrice: 70, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 3 },
      { id: 29, caseId: 'phantom', name: 'Fog SMG', category: 'Пулемёт', rarity: 'rare', sellPrice: 520, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 4 },
      { id: 30, caseId: 'phantom', name: 'Skull AR', category: 'Штурмовая винтовка', rarity: 'rare', sellPrice: 560, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 5 },
      { id: 31, caseId: 'phantom', name: 'Phantom Mask', category: 'Маска', rarity: 'mythical', sellPrice: 1800, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 6 },
      { id: 32, caseId: 'phantom', name: 'Reaper LR-300', category: 'Штурмовая винтовка', rarity: 'mythical', sellPrice: 3600, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 7 },
    ],
  },
  {
    id: 'mystic',
    name: 'Мистический',
    description: '',
    price: 349,
    imageUrl: '/cases/94892be2-5939-43ac-9284-88669f378500.png',
    accent: '#a35bff',
    isActive: true,
    items: [
      { id: 33, caseId: 'mystic', name: 'Starfall Hammer', category: 'Молоток', rarity: 'common', sellPrice: 70, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 0 },
      { id: 34, caseId: 'mystic', name: 'Wizard Hoodie', category: 'Худи', rarity: 'common', sellPrice: 95, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 1 },
      { id: 35, caseId: 'mystic', name: 'Rune Garage', category: 'Гаражная дверь', rarity: 'common', sellPrice: 110, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 2 },
      { id: 36, caseId: 'mystic', name: 'Potion Bag', category: 'Спальный мешок', rarity: 'common', sellPrice: 85, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 3 },
      { id: 37, caseId: 'mystic', name: 'Amethyst MP5', category: 'Пулемёт', rarity: 'rare', sellPrice: 620, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 4 },
      { id: 38, caseId: 'mystic', name: 'Cosmos AR', category: 'Штурмовая винтовка', rarity: 'rare', sellPrice: 680, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 5 },
      { id: 39, caseId: 'mystic', name: 'Nightmare Mask', category: 'Маска', rarity: 'mythical', sellPrice: 2100, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 6 },
      { id: 40, caseId: 'mystic', name: 'Magic Python', category: 'Пистолет', rarity: 'mythical', sellPrice: 4000, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 7 },
    ],
  },
  {
    id: 'gold',
    name: 'Золотой',
    description: '',
    price: 599,
    imageUrl: '/cases/b832a014-5613-40f9-9a01-6fe7d8596eeb.png',
    accent: '#ffb02e',
    isActive: true,
    items: [
      { id: 41, caseId: 'gold', name: 'Nugget Hammer', category: 'Молоток', rarity: 'common', sellPrice: 90, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 0 },
      { id: 42, caseId: 'gold', name: 'Magnate Hoodie', category: 'Худи', rarity: 'common', sellPrice: 120, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 1 },
      { id: 43, caseId: 'gold', name: 'Bullion Garage', category: 'Гаражная дверь', rarity: 'common', sellPrice: 140, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 2 },
      { id: 44, caseId: 'gold', name: 'Luxury Bag', category: 'Спальный мешок', rarity: 'common', sellPrice: 100, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 3 },
      { id: 45, caseId: 'gold', name: 'Luxury Tommy', category: 'Пулемёт', rarity: 'rare', sellPrice: 820, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 4 },
      { id: 46, caseId: 'gold', name: 'Goldrush AR', category: 'Штурмовая винтовка', rarity: 'rare', sellPrice: 900, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 5 },
      { id: 47, caseId: 'gold', name: 'Pharaoh Mask', category: 'Маска', rarity: 'mythical', sellPrice: 2800, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 6 },
      { id: 48, caseId: 'gold', name: 'Golden Age M39', category: 'Штурмовая винтовка', rarity: 'mythical', sellPrice: 5200, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 7 },
    ],
  },
  {
    id: 'clown',
    name: 'Клоун',
    description: '',
    price: 799,
    imageUrl: '/cases/bb949fff-ea37-40b5-a9b6-3aa01613a3d5.png',
    accent: '#ff5ec4',
    isActive: true,
    items: [
      { id: 49, caseId: 'clown', name: 'Clown Hammer', category: 'Молоток', rarity: 'common', sellPrice: 110, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 0 },
      { id: 50, caseId: 'clown', name: 'Clown Hoodie', category: 'Худи', rarity: 'common', sellPrice: 140, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 1 },
      { id: 51, caseId: 'clown', name: 'Clown Garage', category: 'Гаражная дверь', rarity: 'common', sellPrice: 160, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 2 },
      { id: 52, caseId: 'clown', name: 'Clown Sleeping Bag', category: 'Спальный мешок', rarity: 'common', sellPrice: 120, imageUrl: null, dropChance: 45, isActive: true, isFake: false, sortOrder: 3 },
      { id: 53, caseId: 'clown', name: 'Clown MP5', category: 'Пулемёт', rarity: 'rare', sellPrice: 950, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 4 },
      { id: 54, caseId: 'clown', name: 'Clown AR', category: 'Штурмовая винтовка', rarity: 'rare', sellPrice: 1050, imageUrl: null, dropChance: 12, isActive: true, isFake: false, sortOrder: 5 },
      { id: 55, caseId: 'clown', name: 'Big Grin', category: 'Маска', rarity: 'mythical', sellPrice: 3200, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 6 },
      { id: 56, caseId: 'clown', name: 'Tempered AK', category: 'Штурмовая винтовка', rarity: 'mythical', sellPrice: 6000, imageUrl: null, dropChance: 3, isActive: true, isFake: false, sortOrder: 7 },
    ],
  },
];

